title: conail.net
email: info@conail.net
description: "turtles all the way down."
baseurl: ""
url: "http://conail.github.io/"
twitter_username: conail
github_username: conail
markdown: kramdown
permalink: pretty
highlighter: rouge
